# Generated by Django 4.0.5 on 2022-06-17 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_comment_branch_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
    ]
