# Generated by Django 4.0.5 on 2022-06-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_items', to='blog.comment'),
        ),
    ]
