# Generated by Django 4.0.5 on 2022-06-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_born',
            field=models.IntegerField(),
        ),
    ]
