# Generated by Django 4.0.4 on 2022-06-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_user', '0002_alter_author_year_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='', upload_to='book_user/img/authors'),
        ),
    ]
