# Generated by Django 4.0.4 on 2022-05-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_user', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
